#!/bin/sh
# fetch script

host="$(hostname)"
os='Arch Linux'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename "$SHELL")"
uitype="WM"
ui="i3"

# colors
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
as="${reset}${cyan}"         # ascii
hn="${reset}"                # hostname
lc="${reset}${bold}${red}"   # label
ic="${reset}"                # info

# write
cat <<EOF

${as}        /\\         ${hn}${USER}${lc}@${hn}${host}${reset}
${as}       /  \\        ${lc}OS       ${ic}${os}${reset}
${as}      /\\   \\       ${lc}KERNEL   ${ic}${kernel}${reset}
${as}     /  __  \\      ${lc}UPTIME   ${ic}${uptime}${reset}
${as}    /  (  )  \\     ${lc}PACKAGES ${ic}${packages}${reset}
${as}   / __|  |__\\\\    ${lc}SHELL    ${ic}${shell}${reset}
${as}  /.\`        \`.\\   ${lc}${uitype}       ${ic}${ui}${reset}

EOF
